spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/employee_directory?useSSL=false&serverTimeZone=UTC"
    username: springstudent
    password: springstudent

management:
  endpoints:
    web:
      exposure:
        include: "*"
